services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
      - llm-networks

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - .:/opt/app
    restart: always
    ports:
      - "8000:8000" 
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - DOCS_PATH=${DOCS_PATH}
      - TZ=Asia/Jakarta
    networks:
      - llm-networks

networks:
  llm-networks:
    driver: bridge